simulation_metadata:
  device: 'cpu'
  num_episodes: 1
  num_steps_per_episode: 2
  num_substeps_per_step: 5
  calibration: false
  visualize: true
  cesium_token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI2MzllOTJmMy01YmUzLTQwZDQtOGMyYy04NDdlODUyYjc1MzYiLCJpZCI6MjM1NDMxLCJpYXQiOjE3MjM5ODc4ODZ9.CxqymuvZilCWP8dv01j-4634W7PQhcI_DuT-gfRS3dc'

  num_bap: 8961
  num_bpp: 3840
  num_bg: 1
  num_order: 99999

state:
  environment:
    last_order_id:
      shape: [1]
      dtype: 'int'
      value: -1
  network: null

  agents:
    bap:
      number: ${simulation_metadata.num_bap}
      properties:
        id:
          shape: [1]
          dype: 'int'
          initialization_function:
            generator: 'generate_ids'
            arguments:
              shape:
                shape: [2]
                value:
                  - ${state.agents.bap.number}
                  - 1
        position:
          shape: [2]
          dtype: 'int'
          initialization_function:
            generator: 'read_from_file'
            arguments:
              file_path:
                value: './data/simulator/bap/position.csv'
        resource_demand:
          shape: [1]
          dtype: 'float'
          initialization_function:
            generator: 'random_float'
            arguments:
              lower_limit:
                value: 7.42
              upper_limit:
                value: 1269.24
        current_order:
          shape: [1]
          dtype: 'int'
          value: -1 # -1 indicates no active order
        wallet:
          shape: [1]
          dtype: 'float'
          initialization_function:
            generator: 'read_from_file'
            arguments:
              file_path:
                value: './data/simulator/bap/income.csv'

    bpp:
      number: ${simulation_metadata.num_bpp}
      properties:
        id:
          shape: [1]
          dtype: 'int'
          initialization_function:
            generator: 'generate_ids'
            arguments:
              shape:
                shape: [2]
                value:
                  - ${state.agents.bpp.number}
                  - 1
        position:
          shape: [2]
          dtype: 'float'
          initialization_function:
            generator: 'read_from_file'
            arguments:
              file_path:
                value: './data/simulator/bpp/position.csv'
        revenue:
          shape: [1]
          dtype: 'float'
          value: 0
        price:
          learnable: true
          shape: [1]
          dtype: 'float'
          initialization_function:
            generator: 'random_float'
            arguments:
              lower_limit:
                value: 0.25
              upper_limit:
                value: 0.45
        max_capacity:
          shape: [1]
          dtype: 'float'
          initialization_function:
            generator: 'read_from_file'
            arguments:
              file_path:
                value: './data/simulator/bpp/capacity.csv'
        available_capacity:
          shape: [1]
          dtype: 'float'
          initialization_function:
            generator: 'read_from_file'
            arguments:
              file_path:
                value: './data/simulator/bpp/capacity.csv'

    bg:
      number: ${simulation_metadata.num_bg}
      properties:
        id:
          shape: [1]
          dtype: 'int'
          initialization_function:
            generator: 'generate_ids'
            arguments:
              shape:
                shape: [2]
                value:
                  - ${state.agents.bg.number}
                  - 1
        network_traffic:
          shape: [1]
          dtype: 'int'
          value: 0

  objects:
    order:
      number: ${simulation_metadata.num_order}
      properties:
        id:
          shape: [1]
          dtype: 'int'
          initialization_function:
            generator: 'generate_ids'
            arguments:
              shape:
                shape: [2]
                value:
                  - ${state.objects.order.number}
                  - 1
        bap_id:
          shape: [1]
          dtype: 'int'
          value: -1
        bpp_id:
          shape: [1]
          dtype: 'int'
          value: -1
        quantity:
          shape: [1]
          dtype: 'float'
          value: -1
        status:
          shape: [1]
          dtype: 'int' # 0: Created, 1: Confirmed, 2: In Progress, 3: Completed, 4: Cancelled
          value: -1

substeps:
  '0':
    name: 'Search and Select'
    description: 'Search and select an appropriate BPP'
    active_agents:
      - 'bap'
    observation:
      bap:
        find_nearby_bpps:
          generator: 'FindNearbyBPPs'
          arguments: null
          input_variables:
            bap_positions: 'agents/bap/position'
            bpp_positions: 'agents/bpp/position'
          output_variables:
            - distances
            - mask
    policy:
      bap:
        select_bpp:
          generator: 'SelectBPP'
          arguments: null
          input_variables:
            bpp_prices: 'agents/bpp/price'
            bpp_capacity: 'agents/bpp/available_capacity'
            resource_demand: 'agents/bap/resource_demand'
          output_variables:
            - selected_bpps
    transition:
      create_order:
        generator: 'CreateOrder'
        arguments: null
        input_variables:
          bap_id: 'agents/bap/id'
          resource_demand: 'agents/bap/resource_demand'
          last_order_id: 'environment/last_order_id'
          order_bap_id: 'objects/order/bap_id'
          order_bpp_id: 'objects/order/bpp_id'
          order_quantity: 'objects/order/quantity'
          order_status: 'objects/order/status'
        output_variables:
          - order_bap_id
          - order_bpp_id
          - order_quantity
          - order_status

  '1':
    name: 'Confirm'
    description: 'BPP confirms the order'
    active_agents:
      - 'bpp'
    observation:
      bpp:
        check_availability:
          generator: 'CheckAvailability'
          arguments: null
          input_variables:
            bpp_capacity: 'agents/bpp/available_capacity'
          output_variables:
            - is_available
    policy:
      bpp:
        confirm_order:
          generator: 'ConfirmOrder'
          arguments: null
          input_variables: null
          output_variables:
            - order_confirmation
    transition:
      update_order_status:
        generator: 'UpdateOrderStatus'
        arguments: null
        input_variables:
          bpp_capacity: 'agents/bpp/available_capacity'
          order_bpp_id: 'objects/order/bpp_id'
          order_status: 'objects/order/status'
        output_variables:
          - order_status
          - bpp_capacity

  '2':
    name: 'Fulfill'
    description: 'BAP receives service from BPP'
    active_agents:
      - 'bap'
    observation:
      bap: null
    policy:
      bap:
        consume_service:
          generator: 'ConsumeService'
          arguments: null
          input_variables:
            order_bap_id: 'objects/order/bap_id'
            order_bpp_id: 'objects/order/bpp_id'
            order_status: 'objects/order/status'
            bap_res: 'agents/bap/resource_demand'
          output_variables:
            - service_progress
            - involved_baps
            - involved_bpps
            - orders_to_update
    transition:
      update_resources:
        generator: 'UpdateResources'
        arguments: null
        input_variables:
          bap_res: 'agents/bap/resource_demand'
          bpp_cap: 'agents/bpp/available_capacity'
          order_status: 'objects/order/status'
        output_variables:
          - bap_res
          - bpp_cap
          - order_status

  '3':
    name: 'Pay'
    description: 'BAP pays for the service'
    active_agents:
      - 'bap'
    observation:
      bap:
        get_order_details:
          generator: 'GetOrderDetails'
          arguments: null
          input_variables:
            order_bap_id: 'objects/order/bap_id'
            order_bpp_id: 'objects/order/bpp_id'
            order_status: 'objects/order/status'
          output_variables:
            - involved_baps
            - involved_bpps
            - orders_to_update
    policy:
      bap:
        calculate_payment:
          generator: 'CalculatePayment'
          arguments: null
          input_variables:
            bpp_price: 'agents/bpp/price'
            order_quantity: 'objects/order/quantity'
          output_variables:
            - payments_to_make
            - involved_baps
            - involved_bpps
    transition:
      update_wallets:
        generator: 'UpdateWallets'
        arguments: null
        input_variables:
          bap_wallet: 'agents/bap/wallet'
          bpp_revenue: 'agents/bpp/revenue'
        output_variables:
          - bap_wallet
          - bpp_revenue

  '4':
    name: 'Restock'
    description: 'BPP restocks the service'
    active_agents:
      - 'bap'
      - 'bpp'
    observation:
      bap: null
      bpp: null
    policy:
      bap:
        calculate_salary:
          generator: 'CalculateSalary'
          arguments: null
          input_variables:
            bap_wallet: 'agents/bap/wallet'
          output_variables:
            - bap_wallet
      bpp:
        calculate_availability:
          generator: 'CalculateAvailability'
          arguments: null
          input_variables:
            bpp_capacity: 'agents/bpp/available_capacity'
            bpp_max_capacity: 'agents/bpp/max_capacity'
          output_variables:
            - bpp_capacity
    transition:
      update_bpp_availability_and_bap_wallet:
        generator: 'UpdateBPPAvailabilityAndBPPWallet'
        arguments: null
        input_variables:
          bap_wallet: 'agents/bap/wallet'
          bpp_capacity: 'agents/bpp/available_capacity'
        output_variables:
          - bap_wallet
          - bpp_capacity
